- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  # LOP edit
  whitelisted: false # LOP edit
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-prisoner
  displayWeight: 10 # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant ] # Frontier
  - !type:GiveItemOnHolidaySpecial # Frontier: even prisoners get a piece of cake (with no file inside).
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetGrey
