- type: job
  id: Deputy
  name: job-name-deputy
  description: job-description-deputy
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # LOP edit 43200<36000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 180000 # LOP edit 360000<180000
  startingGear: DeputyGear
  icon: JobIconDeputy
  supervisors: job-supervisors-sergeant
  weight: 130
  displayWeight: 40
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DeputyGear
  equipment:
    pocket1: LPPWeaponPistolninemile # LOP edit: WeaponPistolMk58<LPPWeaponPistolninemile
  storage:
    back:
    - Flash
    - MagazinePistol
    - NFMagazinePistol35Rubber
    - FrontierUplinkCoin10
